// @ts-check

/**
 * Autogenerated sidebar from the docs folder structure.
 * Category labels and order are controlled by `_category_.json`
 * and page `sidebar_position` / `sidebar_label` front matter.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
